/*
 * Copyright (C) 2014 e-werkzeug <administrator@e-werkzeug.eu>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

package de.ewerkzeug.easytranscript.GUI.Components;

import static de.ewerkzeug.easytranscript.Core.Easytranscript.terminate;
import static de.ewerkzeug.easytranscript.Core.V.logger;
import de.ewerkzeug.easytranscript.Tools.Tools;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
*
* @author e-werkzeug <administrator@e-werkzeug.eu>
*/
public class Easynews extends javax.swing.JFrame {
List<String> lines = new ArrayList<>();
    /**
* Creates new form easynews
*/
    public Easynews() {
        initComponents();
        
        if (new File("updinf").exists()){
             BufferedReader buffReader;
        try{
            buffReader = new BufferedReader (new FileReader("updinf"));
           
            lines.add(buffReader.readLine());
           if (!lines.get(0).contains("e-werkzeug.eu") &&!lines.get(0).contains("youtube.com/") ){
               JOptionPane.showMessageDialog(null, "<html><b><h3>Update-Information file with prohibited data detected!</h3></b></html>\n\nPlease download easytranscript only through the official Web site or from the specified software sites.\nOtherwise, it may be a dangerous and modified version, which harms your computer\n\neasytranscript will now be closed.", "Corrupt File", JOptionPane.ERROR_MESSAGE);
               logger.log(Level.SEVERE,"updinf with prohibited data.");
               terminate();
              
           }
  
 } catch (IOException ex) {
                Logger.getLogger(Easynews.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        this.setLocationRelativeTo(null);
    }

    /**
* This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
*/
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newsMainlabel = new javax.swing.JLabel();
        newsTextLabel = new javax.swing.JLabel();
        newsBigButtonPanel = new javax.swing.JPanel();
        newsBigButton = new javax.swing.JButton();
        newsBottomPanel = new javax.swing.JPanel();
        newsCloseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("News");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        newsMainlabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de/ewerkzeug/easytranscript/Core/Bundles/Bundle"); // NOI18N
        newsMainlabel.setText(bundle.getString("easynews.title")); // NOI18N

        newsTextLabel.setText(bundle.getString("easynews.text")); // NOI18N

        newsBigButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/ewerkzeug/easytranscript/Core/Images/update-product_l.png"))); // NOI18N
        newsBigButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newsBigButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newsBigButtonPanelLayout = new javax.swing.GroupLayout(newsBigButtonPanel);
        newsBigButtonPanel.setLayout(newsBigButtonPanelLayout);
        newsBigButtonPanelLayout.setHorizontalGroup(
            newsBigButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newsBigButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        newsBigButtonPanelLayout.setVerticalGroup(
            newsBigButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newsBigButtonPanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(newsBigButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        newsCloseButton.setText(bundle.getString("Easytranscript.ZeitCloseButton.text")); // NOI18N
        newsCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newsCloseButtonActionPerformed(evt);
            }
        });
        newsBottomPanel.add(newsCloseButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newsBigButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newsMainlabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(newsTextLabel)))
                        .addGap(0, 24, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(newsBottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newsMainlabel)
                .addGap(18, 18, 18)
                .addComponent(newsTextLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(newsBigButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(newsBottomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newsBigButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newsBigButtonActionPerformed
    new Tools().browse(lines.get(0));

    }//GEN-LAST:event_newsBigButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        new File("updinf").delete();
        
    }//GEN-LAST:event_formWindowClosing

    private void newsCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newsCloseButtonActionPerformed
         new File("updinf").delete();
        dispose();
    }//GEN-LAST:event_newsCloseButtonActionPerformed


public void setVisible(){
    if (lines.isEmpty()==false){
        setVisible(true);
    }
}
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton newsBigButton;
    private javax.swing.JPanel newsBigButtonPanel;
    private javax.swing.JPanel newsBottomPanel;
    private javax.swing.JButton newsCloseButton;
    private javax.swing.JLabel newsMainlabel;
    private javax.swing.JLabel newsTextLabel;
    // End of variables declaration//GEN-END:variables
}