/*
 * Copyright (C) 2014 e-werkzeug <administrator@e-werkzeug.eu>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package de.ewerkzeug.easytranscript.GUI.Components;

import de.ewerkzeug.easytranscript.Core.Easytranscript;
import de.ewerkzeug.easytranscript.Core.V;
import static de.ewerkzeug.easytranscript.Core.V.currentLocale;
import static de.ewerkzeug.easytranscript.Core.V.logger;
import static de.ewerkzeug.easytranscript.Core.V.opFolder;

import de.ewerkzeug.easytranscript.Tools.Tools;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 *
 * @author e-werkzeug <administrator@e-werkzeug.eu>
 */
public class InfoFrame extends javax.swing.JFrame {

    /**
     * Creates new form InfoFrame
     */
    public InfoFrame() {
        initComponents();

        setLocationRelativeTo(null);
        try {

            InfoTextPane.setPage(Easytranscript.class.getResource("Bundles/info_" + currentLocale.getLanguage() + ".html"));
        } catch (IOException ex) {
            Logger.getLogger(InfoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    static URL fileToURL(File file) {
        URL url = null;
        try {
            url = new URL("file://" + file.getPath());
            // Sonderzeichen (z.B. Leerzeichen) bleiben erhalten

            // Sonderzeichen (z.B. Leerzeichen) werden codiert
            url = file.toURI().toURL();

        } catch (MalformedURLException e) {
            logger.log(Level.WARNING, e.getLocalizedMessage());
        }
        return url;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InfoMainPanel = new javax.swing.JPanel();
        InfoTextPanel = new javax.swing.JPanel();
        InfoScrollPane = new javax.swing.JScrollPane();
        InfoTextPane = new javax.swing.JTextPane();
        InfoButtonPanel = new javax.swing.JPanel();
        InfoOKButton = new javax.swing.JButton();
        InfoHomepageButton = new javax.swing.JButton();
        InfoHelpButton = new javax.swing.JButton();
        analysebutton = new javax.swing.JButton();
        logsButton = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de/ewerkzeug/easytranscript/Core/Bundles/Bundle"); // NOI18N
        setTitle(bundle.getString("Easytranscript.MaininfoMenuitem.text")); // NOI18N
        setPreferredSize(new java.awt.Dimension(754, 885));
        setResizable(false);

        InfoMainPanel.setMinimumSize(new java.awt.Dimension(732, 608));
        InfoMainPanel.setName(""); // NOI18N

        InfoTextPane.setEditable(false);
        InfoTextPane.setContentType("text/html"); // NOI18N
        InfoTextPane.setText(bundle.getString("Easytranscript.InfoTextPane.text")); // NOI18N
        InfoScrollPane.setViewportView(InfoTextPane);

        javax.swing.GroupLayout InfoTextPanelLayout = new javax.swing.GroupLayout(InfoTextPanel);
        InfoTextPanel.setLayout(InfoTextPanelLayout);
        InfoTextPanelLayout.setHorizontalGroup(
            InfoTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoTextPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InfoScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InfoTextPanelLayout.setVerticalGroup(
            InfoTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoTextPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InfoScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        InfoOKButton.setText(bundle.getString("Easytranscript.InfoOKButton.text")); // NOI18N
        InfoOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoOKButtonActionPerformed(evt);
            }
        });
        InfoButtonPanel.add(InfoOKButton);

        InfoHomepageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/ewerkzeug/easytranscript/Core/Images/go-home-8.png"))); // NOI18N
        InfoHomepageButton.setText(bundle.getString("Easytranscript.InfoHomepageButton.text")); // NOI18N
        InfoHomepageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoHomepageButtonActionPerformed(evt);
            }
        });

        InfoHelpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/ewerkzeug/easytranscript/Core/Images/help-hint.png"))); // NOI18N
        InfoHelpButton.setText(bundle.getString("Easytranscript.InfoHelpButton.text")); // NOI18N
        InfoHelpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoHelpButtonActionPerformed(evt);
            }
        });

        analysebutton.setText(bundle.getString("info.systemanalyse")); // NOI18N
        analysebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analysebuttonActionPerformed(evt);
            }
        });

        logsButton.setText(bundle.getString("logsFolderButtonText")); // NOI18N
        logsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InfoMainPanelLayout = new javax.swing.GroupLayout(InfoMainPanel);
        InfoMainPanel.setLayout(InfoMainPanelLayout);
        InfoMainPanelLayout.setHorizontalGroup(
            InfoMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InfoButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfoMainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(analysebutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InfoHelpButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InfoHomepageButton)
                .addContainerGap())
            .addGroup(InfoMainPanelLayout.createSequentialGroup()
                .addComponent(InfoTextPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        InfoMainPanelLayout.setVerticalGroup(
            InfoMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoMainPanelLayout.createSequentialGroup()
                .addComponent(InfoTextPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InfoMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(InfoMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(analysebutton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(InfoMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InfoHomepageButton)
                            .addComponent(InfoHelpButton))))
                .addGap(24, 24, 24)
                .addComponent(InfoButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InfoMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(InfoMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InfoOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoOKButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_InfoOKButtonActionPerformed

    private void InfoHomepageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoHomepageButtonActionPerformed
        new Tools().browse("http://e-werkzeug.eu/");

    }//GEN-LAST:event_InfoHomepageButtonActionPerformed

    private void InfoHelpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoHelpButtonActionPerformed

        new Tools().browse("http://e-werkzeug.eu/software/easytranscript/versions/" + V.VERSION.getMajorVersion() + "." + V.VERSION.getMinorVersion() + "/help/" + currentLocale.getLanguage() + "/");
    }//GEN-LAST:event_InfoHelpButtonActionPerformed

    private void analysebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analysebuttonActionPerformed
        try {
            Runtime.getRuntime().exec("java -jar easysysteminspector.jar");
        } catch (IOException ex) {
            Logger.getLogger(InfoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_analysebuttonActionPerformed

    private void logsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logsButtonActionPerformed

        try {

            Desktop.getDesktop().open(new File(opFolder + "Logs/"));
        } catch (Exception ex) {

            logger.log(Level.SEVERE, ex.getLocalizedMessage());
            JOptionPane.showMessageDialog(null, ex.getLocalizedMessage(), "", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_logsButtonActionPerformed

    public JScrollPane getInfoScrollPane() {
        return InfoScrollPane;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel InfoButtonPanel;
    private javax.swing.JButton InfoHelpButton;
    private javax.swing.JButton InfoHomepageButton;
    private javax.swing.JPanel InfoMainPanel;
    private javax.swing.JButton InfoOKButton;
    private javax.swing.JScrollPane InfoScrollPane;
    private javax.swing.JTextPane InfoTextPane;
    private javax.swing.JPanel InfoTextPanel;
    private javax.swing.JButton analysebutton;
    private javax.swing.JButton logsButton;
    // End of variables declaration//GEN-END:variables
}
