/*
 * Copyright (C) 2014 e-werkzeug <administrator@e-werkzeug.eu>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

package de.ewerkzeug.easytranscript.gui.components;

import de.ewerkzeug.easytranscript.core.Variables;
import de.ewerkzeug.easytranscript.tools.Finder;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author e-werkzeug <administrator@e-werkzeug.eu>
 */
public class SearchFrame extends javax.swing.JFrame {

    /**
     * Creates new form SearchFrame
     */
    public SearchFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchButtongroup = new javax.swing.ButtonGroup();
        SearchSearchphraseTextfield = new javax.swing.JTextField();
        SearchSearchLabel = new javax.swing.JLabel();
        SearchNextButton = new javax.swing.JButton();
        SearchReplaceLabel = new javax.swing.JLabel();
        SearchReplaceTextfield = new javax.swing.JTextField();
        SearchReplaceButton = new javax.swing.JButton();
        SearchReplaceAllButton = new javax.swing.JButton();
        SearchCaseSensitiveCheckbox = new javax.swing.JCheckBox();
        SearchBottomPanel = new javax.swing.JPanel();
        SearchCloseButton = new javax.swing.JButton();
        SearchUpwardsRadiobutton = new javax.swing.JRadioButton();
        SearchDownwardsRadiobutton = new javax.swing.JRadioButton();
        SearchOnlyWholeWordsCheckbox = new javax.swing.JCheckBox();
        SearchStatus1Label = new javax.swing.JLabel();
        SearchStatus2Label = new javax.swing.JLabel();
        regexSearchCheckbox = new javax.swing.JCheckBox();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de/ewerkzeug/easytranscript/core/bundles/Bundle"); // NOI18N
        setTitle(bundle.getString("Easytranscript.MainsearchReplaceMenuitem.text")); // NOI18N
        setResizable(false);

        SearchSearchphraseTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchSearchphraseTextfieldActionPerformed(evt);
            }
        });

        SearchSearchLabel.setText(bundle.getString("Easytranscript.SearchSearchLabel.text")); // NOI18N

        SearchNextButton.setText(bundle.getString("Easytranscript.SearchNextButton.text")); // NOI18N
        SearchNextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchNextButtonActionPerformed(evt);
            }
        });

        SearchReplaceLabel.setText(bundle.getString("Easytranscript.SearchReplaceLabel.text")); // NOI18N

        SearchReplaceButton.setText(bundle.getString("Easytranscript.SearchReplaceButton.text")); // NOI18N
        SearchReplaceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchReplaceButtonActionPerformed(evt);
            }
        });

        SearchReplaceAllButton.setText(bundle.getString("Easytranscript.SearchReplaceAllButton.text")); // NOI18N
        SearchReplaceAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchReplaceAllButtonActionPerformed(evt);
            }
        });

        SearchCaseSensitiveCheckbox.setText(bundle.getString("Easytranscript.SearchCaseSensitiveCheckbox.text")); // NOI18N
        SearchCaseSensitiveCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchCaseSensitiveCheckboxActionPerformed(evt);
            }
        });

        SearchCloseButton.setText(bundle.getString("Easytranscript.SearchCloseButton.text")); // NOI18N
        SearchCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchCloseButtonActionPerformed(evt);
            }
        });
        SearchBottomPanel.add(SearchCloseButton);

        SearchButtongroup.add(SearchUpwardsRadiobutton);
        SearchUpwardsRadiobutton.setText(bundle.getString("Easytranscript.SearchUpwardsRadiobutton.text")); // NOI18N

        SearchButtongroup.add(SearchDownwardsRadiobutton);
        SearchDownwardsRadiobutton.setSelected(true);
        SearchDownwardsRadiobutton.setText(bundle.getString("Easytranscript.SearchDownwardsRadiobutton.text")); // NOI18N

        SearchOnlyWholeWordsCheckbox.setText(bundle.getString("Easytranscript.SearchOnlyWholeWordsCheckbox.text")); // NOI18N

        SearchStatus1Label.setForeground(new java.awt.Color(204, 0, 0));
        SearchStatus1Label.setText(bundle.getString("Easytranscript.SearchStatus1Label.text")); // NOI18N

        SearchStatus2Label.setText(bundle.getString("Easytranscript.SearchStatus2Label.text")); // NOI18N

        regexSearchCheckbox.setText(bundle.getString("RegexSearch")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SearchBottomPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(SearchReplaceLabel)
                                    .addComponent(SearchSearchLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SearchReplaceTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                                    .addComponent(SearchSearchphraseTextfield)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SearchCaseSensitiveCheckbox)
                                    .addComponent(SearchOnlyWholeWordsCheckbox)
                                    .addComponent(regexSearchCheckbox))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SearchDownwardsRadiobutton)
                                    .addComponent(SearchUpwardsRadiobutton))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SearchReplaceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SearchReplaceAllButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SearchNextButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SearchStatus1Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchStatus2Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SearchNextButton)
                        .addGap(18, 18, 18)
                        .addComponent(SearchReplaceButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchReplaceAllButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(SearchReplaceLabel)
                                    .addComponent(SearchReplaceTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SearchSearchphraseTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SearchSearchLabel)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SearchCaseSensitiveCheckbox)
                            .addComponent(SearchUpwardsRadiobutton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SearchDownwardsRadiobutton)
                            .addComponent(SearchOnlyWholeWordsCheckbox))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(regexSearchCheckbox)
                .addGap(18, 18, 18)
                .addComponent(SearchBottomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchStatus1Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SearchStatus2Label))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchNextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchNextButtonActionPerformed
        Finder.searchForMatch();

    }//GEN-LAST:event_SearchNextButtonActionPerformed

    private void SearchReplaceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchReplaceButtonActionPerformed

        Finder.replace();
    }//GEN-LAST:event_SearchReplaceButtonActionPerformed

    @SuppressWarnings("empty-statement")
    private void SearchReplaceAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchReplaceAllButtonActionPerformed
        Variables.searchFrame.setVisible(false);
        while (Finder.replace() > -1);
        Variables.searchFrame.setVisible(true);
    }//GEN-LAST:event_SearchReplaceAllButtonActionPerformed

    private void SearchCaseSensitiveCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchCaseSensitiveCheckboxActionPerformed

    }//GEN-LAST:event_SearchCaseSensitiveCheckboxActionPerformed

    private void SearchCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchCloseButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_SearchCloseButtonActionPerformed

    private void SearchSearchphraseTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchSearchphraseTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchSearchphraseTextfieldActionPerformed

    public JCheckBox getSearchCaseSensitiveCheckbox() {
        return SearchCaseSensitiveCheckbox;
    }
     public JCheckBox getRegexSearchCheckbox() {
        return this.regexSearchCheckbox;
    }

    public JRadioButton getSearchDownwardsRadiobutton() {
        return SearchDownwardsRadiobutton;
    }

    public JCheckBox getSearchOnlyWholeWordsCheckbox() {
        return SearchOnlyWholeWordsCheckbox;
    }

    public JTextField getSearchReplaceTextfield() {
        return SearchReplaceTextfield;
    }

    public JTextField getSearchSearchphraseTextfield() {
        return SearchSearchphraseTextfield;
    }

    public JLabel getSearchStatus1Label() {
        return SearchStatus1Label;
    }

    public JLabel getSearchStatus2Label() {
        return SearchStatus2Label;
    }

    public JRadioButton getSearchUpwardsRadiobutton() {
        return SearchUpwardsRadiobutton;
    }

   
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SearchBottomPanel;
    private javax.swing.ButtonGroup SearchButtongroup;
    private javax.swing.JCheckBox SearchCaseSensitiveCheckbox;
    private javax.swing.JButton SearchCloseButton;
    private javax.swing.JRadioButton SearchDownwardsRadiobutton;
    private javax.swing.JButton SearchNextButton;
    private javax.swing.JCheckBox SearchOnlyWholeWordsCheckbox;
    private javax.swing.JButton SearchReplaceAllButton;
    private javax.swing.JButton SearchReplaceButton;
    private javax.swing.JLabel SearchReplaceLabel;
    private javax.swing.JTextField SearchReplaceTextfield;
    private javax.swing.JLabel SearchSearchLabel;
    private javax.swing.JTextField SearchSearchphraseTextfield;
    private javax.swing.JLabel SearchStatus1Label;
    private javax.swing.JLabel SearchStatus2Label;
    private javax.swing.JRadioButton SearchUpwardsRadiobutton;
    private javax.swing.JCheckBox regexSearchCheckbox;
    // End of variables declaration//GEN-END:variables
}
