/*
 * Copyright (C) 2014 e-werkzeug <administrator@e-werkzeug.eu>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package de.ewerkzeug.easytranscript.gui.components;

import static de.ewerkzeug.easytranscript.core.Easytranscript.MaincreateProjectMenuItem;
import static de.ewerkzeug.easytranscript.core.Easytranscript.MainimportProjectMenuItem;
import de.ewerkzeug.easytranscript.core.ErrorReport;
import de.ewerkzeug.easytranscript.core.Variables;
import static de.ewerkzeug.easytranscript.core.Variables.currentLocale;
import static de.ewerkzeug.easytranscript.core.Variables.easytranscript;
import static de.ewerkzeug.easytranscript.core.Variables.errors;
import static de.ewerkzeug.easytranscript.core.Variables.logger;
import static de.ewerkzeug.easytranscript.core.Variables.messages;
import static de.ewerkzeug.easytranscript.core.Variables.opFolder;
import static de.ewerkzeug.easytranscript.core.Variables.projFolder;
import static de.ewerkzeug.easytranscript.core.Variables.prop;
import static de.ewerkzeug.easytranscript.core.Variables.startRecentUsed;
import de.ewerkzeug.easytranscript.IO.data.TranscriptHandler;
import de.ewerkzeug.easytranscript.tools.Tools;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import javax.swing.JFileChooser;
import javax.swing.JMenuItem;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author e-werkzeug <administrator@e-werkzeug.eu>
 */
public class StartFrame extends javax.swing.JFrame {

    /**
     * Creates new form StartFrame
     */
    public StartFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StartMainPanel = new javax.swing.JPanel();
        StartMidPanel = new javax.swing.JPanel();
        StartcreateButton = new javax.swing.JButton();
        StartloadButton = new javax.swing.JButton();
        StartloadRecentButton = new javax.swing.JButton();
        StartimportButton = new javax.swing.JButton();
        StarthelpButton = new javax.swing.JButton();
        StarthomeButton = new javax.swing.JButton();
        StartspendButton = new javax.swing.JButton();
        StarthideCheckbox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        StartsocialButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("easytranscript");
        setResizable(false);

        //StartMainPanel.setBackground(new java.awt.Color(250, 250, 250));
        StartMainPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StartMainPanelMouseClicked(evt);
            }
        });

        //StartMidPanel.setBackground(new java.awt.Color(250, 250, 250));

        StartcreateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/ewerkzeug/easytranscript/core/images/document-new-6_big.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de/ewerkzeug/easytranscript/core/bundles/Bundle"); // NOI18N
        StartcreateButton.setText(bundle.getString("Easytranscript.StartcreateButton.text")); // NOI18N
        StartcreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartcreateButtonActionPerformed(evt);
            }
        });

        StartloadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/ewerkzeug/easytranscript/core/images/document-open-8_big.png"))); // NOI18N
        StartloadButton.setText(bundle.getString("Easytranscript.StartloadButton.text")); // NOI18N
        StartloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartloadButtonActionPerformed(evt);
            }
        });

        StartloadRecentButton.setText(bundle.getString("Easytranscript.StartloadRecentButton.text")); // NOI18N
        StartloadRecentButton.setToolTipText(bundle.getString("Easytranscript.MainrecentMenu.text")); // NOI18N
        StartloadRecentButton.setBorderPainted(false);
        StartloadRecentButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                StartloadRecentButtonMousePressed(evt);
            }
        });
        StartloadRecentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartloadRecentButtonActionPerformed(evt);
            }
        });

        StartimportButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/ewerkzeug/easytranscript/core/images/document-import-2.png"))); // NOI18N
        StartimportButton.setText(bundle.getString("Easytranscript.StartimportButton.text")); // NOI18N
        StartimportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartimportButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StartMidPanelLayout = new javax.swing.GroupLayout(StartMidPanel);
        StartMidPanel.setLayout(StartMidPanelLayout);
        StartMidPanelLayout.setHorizontalGroup(
            StartMidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StartMidPanelLayout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addGroup(StartMidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StartimportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(StartMidPanelLayout.createSequentialGroup()
                        .addComponent(StartloadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StartloadRecentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(StartcreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(154, 154, 154))
        );
        StartMidPanelLayout.setVerticalGroup(
            StartMidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StartMidPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StartcreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StartMidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StartloadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StartloadRecentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StartimportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        StarthelpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/ewerkzeug/easytranscript/core/images/help-hint.png"))); // NOI18N
        StarthelpButton.setToolTipText(bundle.getString("Easytranscript.StarthelpButton.toolTipText")); // NOI18N
        StarthelpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StarthelpButtonActionPerformed(evt);
            }
        });

        StarthomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/ewerkzeug/easytranscript/core/images/go-home-8.png"))); // NOI18N
        StarthomeButton.setToolTipText(bundle.getString("Easytranscript.StarthomeButton.toolTipText")); // NOI18N
        StarthomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StarthomeButtonActionPerformed(evt);
            }
        });

        StartspendButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/ewerkzeug/easytranscript/core/images/money.png"))); // NOI18N
        StartspendButton.setToolTipText(bundle.getString("Easytranscript.StartspendButton.toolTipText")); // NOI18N
        StartspendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartspendButtonActionPerformed(evt);
            }
        });

      //  StarthideCheckbox.setBackground(new java.awt.Color(250, 250, 250));
        StarthideCheckbox.setText(bundle.getString("Easytranscript.StarthideCheckbox.text")); // NOI18N
        StarthideCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StarthideCheckboxActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/ewerkzeug/easytranscript/core/images/easy.png"))); // NOI18N

        StartsocialButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/ewerkzeug/easytranscript/core/images/network.png"))); // NOI18N
        StartsocialButton.setToolTipText("social networks");
        StartsocialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartsocialButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StartMainPanelLayout = new javax.swing.GroupLayout(StartMainPanel);
        StartMainPanel.setLayout(StartMainPanelLayout);
        StartMainPanelLayout.setHorizontalGroup(
            StartMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StartMidPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(StartMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StartMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StartMainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(StartMainPanelLayout.createSequentialGroup()
                        .addGroup(StartMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(StartMainPanelLayout.createSequentialGroup()
                                .addComponent(StarthideCheckbox)
                                .addGap(0, 197, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StartMainPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(StartsocialButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StarthomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StarthelpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StartspendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );
        StartMainPanelLayout.setVerticalGroup(
            StartMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StartMidPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 36, Short.MAX_VALUE)
                .addGroup(StartMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StartMainPanelLayout.createSequentialGroup()
                        .addComponent(StarthideCheckbox)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StartMainPanelLayout.createSequentialGroup()
                        .addGroup(StartMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(StartsocialButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(StarthomeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(StarthelpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(StartspendButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StartMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StartMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        StartMainPanel.setVisible(true);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartcreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartcreateButtonActionPerformed
        if (easytranscript.getMainCenterVideoInternalframe().getBorder() != null) {
            easytranscript.getMainCenterVideoInternalframe().setBorder(null);
        }
        MaincreateProjectMenuItem.getActionListeners()[0].actionPerformed(null);
    }//GEN-LAST:event_StartcreateButtonActionPerformed

    private void StartloadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartloadButtonActionPerformed

        if (easytranscript.getMainCenterVideoInternalframe().getBorder() != null) {
            easytranscript.getMainCenterVideoInternalframe().setBorder(null);
        }

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter(messages.getString("etmFiletype"), "etm"));
        fileChooser.setFileFilter(new FileNameExtensionFilter(messages.getString("etpFiletype"), "etp"));
        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.setCurrentDirectory(new File(opFolder + "Projects/"));
        int ruckgabe = fileChooser.showOpenDialog(null);
        fileChooser.getSelectedFile();
        if (ruckgabe == JFileChooser.CANCEL_OPTION) {

            return;
        }

        if (ruckgabe == JFileChooser.APPROVE_OPTION) {
            if (fileChooser.getSelectedFile().getAbsolutePath().endsWith(".etp")) {

                TranscriptHandler.read(fileChooser.getSelectedFile().getAbsolutePath());
            }
            if (fileChooser.getSelectedFile().getAbsolutePath().endsWith(".etm")) {
                dispose();
                projFolder.load(fileChooser.getSelectedFile().getAbsolutePath());

            }
        }

        //  this.MainopenProjectMenuItemActionPerformed(evt);
    }//GEN-LAST:event_StartloadButtonActionPerformed

    private void StartloadRecentButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartloadRecentButtonMousePressed

    }//GEN-LAST:event_StartloadRecentButtonMousePressed

    private void StartimportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartimportButtonActionPerformed

        MainimportProjectMenuItem.getActionListeners()[0].actionPerformed(null);
    }//GEN-LAST:event_StartimportButtonActionPerformed

    private void StarthelpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StarthelpButtonActionPerformed
        //

        new Tools().browse("http://e-werkzeug.eu/software/easytranscript/versions/" + Variables.VERSION.getMajorVersion() + "." + Variables.VERSION.getMinorVersion() + "/help/" + currentLocale.getLanguage() + "/");

    }//GEN-LAST:event_StarthelpButtonActionPerformed

    private void StarthomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StarthomeButtonActionPerformed
        new Tools().browse("http://e-werkzeug.eu/");
    }//GEN-LAST:event_StarthomeButtonActionPerformed

    private void StartspendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartspendButtonActionPerformed

        new Tools().spenden();
    }//GEN-LAST:event_StartspendButtonActionPerformed

    private void StarthideCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StarthideCheckboxActionPerformed
        prop.setBoolProperty("showStart", StarthideCheckbox.isSelected());
        try {
            prop.save();
        } catch (IOException e) {
            logger.log(Level.SEVERE, new ErrorReport().show(errors.getString("SavingConfig2")), e);

        }
        prop.applyProperties();
    }//GEN-LAST:event_StarthideCheckboxActionPerformed

    private void StartMainPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartMainPanelMouseClicked
        if (easytranscript.getMainCenterVideoInternalframe().getBorder() != null) {
            easytranscript.getMainCenterVideoInternalframe().setBorder(null);
        }
    }//GEN-LAST:event_StartMainPanelMouseClicked

    private void StartloadRecentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartloadRecentButtonActionPerformed
        if (easytranscript.getMainCenterVideoInternalframe().getBorder() != null) {
            easytranscript.getMainCenterVideoInternalframe().setBorder(null);
        }

        startRecentUsed.show(StartloadRecentButton, 0, 0);
        startRecentUsed.setBorderPainted(true);
        startRecentUsed.setBorder(new javax.swing.border.EtchedBorder(Color.BLACK, Color.WHITE));
        for (int i = 0; i < 3; i++) {
            if (((JMenuItem) startRecentUsed.getComponent(i)).getText().equals("")) {
                ((JMenuItem) startRecentUsed.getComponent(i)).setVisible(false);
            } else {
                ((JMenuItem) startRecentUsed.getComponent(i)).setVisible(true);
            }
        }
    }//GEN-LAST:event_StartloadRecentButtonActionPerformed

    private void StartsocialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartsocialButtonActionPerformed
        new Tools().social();
    }//GEN-LAST:event_StartsocialButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel StartMainPanel;
    private javax.swing.JPanel StartMidPanel;
    private javax.swing.JButton StartcreateButton;
    private javax.swing.JButton StarthelpButton;
    private javax.swing.JCheckBox StarthideCheckbox;
    private javax.swing.JButton StarthomeButton;
    private javax.swing.JButton StartimportButton;
    private javax.swing.JButton StartloadButton;
    private javax.swing.JButton StartloadRecentButton;
    private javax.swing.JButton StartsocialButton;
    private javax.swing.JButton StartspendButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
