/*
 * Copyright (C) 2014 e-werkzeug <administrator@e-werkzeug.eu>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package de.ewerkzeug.easytranscript.GUI.Components;

import de.ewerkzeug.easytranscript.GUI.Misc.JTextfieldLimit;
import javax.swing.JTextField;

/**
 *
 * @author e-werkzeug <administrator@e-werkzeug.eu>
 */
public class TastenCheckFrame extends javax.swing.JFrame {

    /**
     * Creates new form TastenCheckFrame
     */
    public TastenCheckFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TCkm1Textfield = new javax.swing.JTextField();
        TCtm10Textfield = new JTextfieldLimit(30);
        TCkm2Textfield = new javax.swing.JTextField();
        TCkm3Textfield = new javax.swing.JTextField();
        TCkm4Textfield = new javax.swing.JTextField();
        TCkm5Textfield = new javax.swing.JTextField();
        TCkm6Textfield = new javax.swing.JTextField();
        TCkm7Textfield = new javax.swing.JTextField();
        TCkm8Textfield = new javax.swing.JTextField();
        TCkm9Textfield = new javax.swing.JTextField();
        TCkm10Textfield = new javax.swing.JTextField();
        TCtm9Textfield = new JTextfieldLimit(30);
        TCtm8Textfield = new JTextfieldLimit(30);
        TCtm7Textfield = new JTextfieldLimit(30);
        TCtm6Textfield = new JTextfieldLimit(30);
        TCtm5Textfield = new JTextfieldLimit(30);
        TCtm4Textfield = new JTextfieldLimit(30);
        TCtm3Textfield = new JTextfieldLimit(30);
        TCtm2Textfield = new JTextfieldLimit(30);
        TCtm1Textfield = new JTextfieldLimit(30);
        TCmodulesTitleLabel = new javax.swing.JLabel();
        TCPlayerbackTTextfield = new javax.swing.JTextField();
        TCPlayerplayTTextfield = new javax.swing.JTextField();
        TCPlayerforwTTextfield = new javax.swing.JTextField();
        TCPlayerbackTextfield = new javax.swing.JTextField();
        TCPlayerPlayTextfield = new javax.swing.JTextField();
        TCPlayerforwTextfield = new javax.swing.JTextField();
        TCplayerTitleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de/ewerkzeug/easytranscript/Core/Bundles/Bundle"); // NOI18N
        setTitle(bundle.getString("Easytranscript.MainshortcutsMenuitem.text")); // NOI18N
        setAlwaysOnTop(true);
        setResizable(false);

        TCkm1Textfield.setEditable(false);
        TCkm1Textfield.setText(bundle.getString("Easytranscript.TCkm1Textfield.text")); // NOI18N

        TCtm10Textfield.setEditable(false);
        TCtm10Textfield.setText(bundle.getString("Easytranscript.TCtm10Textfield.text")); // NOI18N

        TCkm2Textfield.setEditable(false);
        TCkm2Textfield.setText(bundle.getString("Easytranscript.TCkm2Textfield.text")); // NOI18N

        TCkm3Textfield.setEditable(false);
        TCkm3Textfield.setText(bundle.getString("Easytranscript.TCkm3Textfield.text")); // NOI18N

        TCkm4Textfield.setEditable(false);
        TCkm4Textfield.setText(bundle.getString("Easytranscript.TCkm4Textfield.text")); // NOI18N

        TCkm5Textfield.setEditable(false);
        TCkm5Textfield.setText(bundle.getString("Easytranscript.TCkm5Textfield.text")); // NOI18N

        TCkm6Textfield.setEditable(false);
        TCkm6Textfield.setText(bundle.getString("Easytranscript.TCkm6Textfield.text")); // NOI18N

        TCkm7Textfield.setEditable(false);
        TCkm7Textfield.setText(bundle.getString("Easytranscript.TCkm7Textfield.text")); // NOI18N

        TCkm8Textfield.setEditable(false);
        TCkm8Textfield.setText(bundle.getString("Easytranscript.TCkm8Textfield.text")); // NOI18N

        TCkm9Textfield.setEditable(false);
        TCkm9Textfield.setText(bundle.getString("Easytranscript.TCkm9Textfield.text")); // NOI18N

        TCkm10Textfield.setEditable(false);
        TCkm10Textfield.setText(bundle.getString("Easytranscript.TCkm10Textfield.text")); // NOI18N

        TCtm9Textfield.setEditable(false);
        TCtm9Textfield.setText(bundle.getString("Easytranscript.TCtm9Textfield.text")); // NOI18N

        TCtm8Textfield.setEditable(false);
        TCtm8Textfield.setText(bundle.getString("Easytranscript.TCtm8Textfield.text")); // NOI18N

        TCtm7Textfield.setEditable(false);
        TCtm7Textfield.setText(bundle.getString("Easytranscript.TCtm7Textfield.text")); // NOI18N

        TCtm6Textfield.setEditable(false);
        TCtm6Textfield.setText(bundle.getString("Easytranscript.TCtm6Textfield.text")); // NOI18N

        TCtm5Textfield.setEditable(false);
        TCtm5Textfield.setText(bundle.getString("Easytranscript.TCtm5Textfield.text")); // NOI18N

        TCtm4Textfield.setEditable(false);
        TCtm4Textfield.setText(bundle.getString("Easytranscript.TCtm4Textfield.text")); // NOI18N

        TCtm3Textfield.setEditable(false);
        TCtm3Textfield.setText(bundle.getString("Easytranscript.TCtm3Textfield.text")); // NOI18N

        TCtm2Textfield.setEditable(false);
        TCtm2Textfield.setText(bundle.getString("Easytranscript.TCtm2Textfield.text")); // NOI18N

        TCtm1Textfield.setEditable(false);
        TCtm1Textfield.setText(bundle.getString("Easytranscript.TCtm1Textfield.text")); // NOI18N

        TCmodulesTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        TCmodulesTitleLabel.setText(bundle.getString("Easytranscript.TCmodulesTitleLabel.text")); // NOI18N

        TCPlayerbackTTextfield.setEditable(false);
        TCPlayerbackTTextfield.setText(bundle.getString("Easytranscript.TCPlayerbackTTextfield.text")); // NOI18N

        TCPlayerplayTTextfield.setEditable(false);
        TCPlayerplayTTextfield.setText(bundle.getString("Easytranscript.TCPlayerplayTTextfield.text")); // NOI18N

        TCPlayerforwTTextfield.setEditable(false);
        TCPlayerforwTTextfield.setText(bundle.getString("Easytranscript.TCPlayerforwTTextfield.text")); // NOI18N

        TCPlayerbackTextfield.setEditable(false);
        TCPlayerbackTextfield.setText(bundle.getString("Easytranscript.TCPlayerbackTextfield.text")); // NOI18N

        TCPlayerPlayTextfield.setEditable(false);
        TCPlayerPlayTextfield.setText(bundle.getString("Easytranscript.TCPlayerPlayTextfield.text")); // NOI18N

        TCPlayerforwTextfield.setEditable(false);
        TCPlayerforwTextfield.setText(bundle.getString("Easytranscript.TCPlayerforwTextfield.text")); // NOI18N

        TCplayerTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        TCplayerTitleLabel.setText(bundle.getString("Easytranscript.TCplayerTitleLabel.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TCmodulesTitleLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TCkm9Textfield)
                                            .addComponent(TCkm8Textfield)
                                            .addComponent(TCkm7Textfield)
                                            .addComponent(TCkm5Textfield, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(TCkm10Textfield)
                                            .addComponent(TCkm6Textfield))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TCkm1Textfield)
                                        .addGap(6, 6, 6)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TCtm6Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TCtm7Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TCtm8Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TCtm9Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TCtm10Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TCtm1Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TCtm5Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(TCkm3Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TCtm3Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(TCkm2Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TCtm2Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TCkm4Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TCtm4Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TCPlayerbackTextfield, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TCPlayerPlayTextfield, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TCPlayerforwTextfield, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TCPlayerforwTTextfield)
                                    .addComponent(TCPlayerplayTTextfield)
                                    .addComponent(TCPlayerbackTTextfield)))))
                    .addComponent(TCplayerTitleLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TCmodulesTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TCtm1Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCkm1Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TCtm2Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCkm2Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TCtm3Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCkm3Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TCtm4Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCkm4Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TCkm5Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCtm5Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TCkm6Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCtm6Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TCkm7Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCtm7Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TCtm8Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCkm8Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TCkm9Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCtm9Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TCkm10Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCtm10Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(TCplayerTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TCPlayerbackTTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCPlayerbackTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TCPlayerplayTTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCPlayerPlayTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TCPlayerforwTTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCPlayerforwTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTextField getTCPlayerPlayTextfield() {
        return TCPlayerPlayTextfield;
    }

    public JTextField getTCPlayerbackTextfield() {
        return TCPlayerbackTextfield;
    }

    public JTextField getTCPlayerforwTextfield() {
        return TCPlayerforwTextfield;
    }

    public JTextField getTCtm10Textfield() {
        return TCtm10Textfield;
    }

    public JTextField getTCtm1Textfield() {
        return TCtm1Textfield;
    }

    public JTextField getTCtm2Textfield() {
        return TCtm2Textfield;
    }

    public JTextField getTCtm3Textfield() {
        return TCtm3Textfield;
    }

    public JTextField getTCtm4Textfield() {
        return TCtm4Textfield;
    }

    public JTextField getTCtm5Textfield() {
        return TCtm5Textfield;
    }

    public JTextField getTCtm6Textfield() {
        return TCtm6Textfield;
    }

    public JTextField getTCtm7Textfield() {
        return TCtm7Textfield;
    }

    public JTextField getTCtm8Textfield() {
        return TCtm8Textfield;
    }

    public JTextField getTCtm9Textfield() {
        return TCtm9Textfield;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TCPlayerPlayTextfield;
    private javax.swing.JTextField TCPlayerbackTTextfield;
    private javax.swing.JTextField TCPlayerbackTextfield;
    private javax.swing.JTextField TCPlayerforwTTextfield;
    private javax.swing.JTextField TCPlayerforwTextfield;
    private javax.swing.JTextField TCPlayerplayTTextfield;
    private javax.swing.JTextField TCkm10Textfield;
    private javax.swing.JTextField TCkm1Textfield;
    private javax.swing.JTextField TCkm2Textfield;
    private javax.swing.JTextField TCkm3Textfield;
    private javax.swing.JTextField TCkm4Textfield;
    private javax.swing.JTextField TCkm5Textfield;
    private javax.swing.JTextField TCkm6Textfield;
    private javax.swing.JTextField TCkm7Textfield;
    private javax.swing.JTextField TCkm8Textfield;
    private javax.swing.JTextField TCkm9Textfield;
    private javax.swing.JLabel TCmodulesTitleLabel;
    private javax.swing.JLabel TCplayerTitleLabel;
    private javax.swing.JTextField TCtm10Textfield;
    private javax.swing.JTextField TCtm1Textfield;
    private javax.swing.JTextField TCtm2Textfield;
    private javax.swing.JTextField TCtm3Textfield;
    private javax.swing.JTextField TCtm4Textfield;
    private javax.swing.JTextField TCtm5Textfield;
    private javax.swing.JTextField TCtm6Textfield;
    private javax.swing.JTextField TCtm7Textfield;
    private javax.swing.JTextField TCtm8Textfield;
    private javax.swing.JTextField TCtm9Textfield;
    // End of variables declaration//GEN-END:variables
}
