/*
 * Copyright (C) 2014 e-werkzeug <administrator@e-werkzeug.eu>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package de.ewerkzeug.easytranscript.GUI.Components;

import static de.ewerkzeug.easytranscript.Core.V.messages;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author e-werkzeug <administrator@e-werkzeug.eu>
 */
public class YotubeFrame extends javax.swing.JFrame {

    String mydata = "";

    /**
     * Creates new form YotubeFrame
     *
     * @param mydata
     */
    public YotubeFrame(String mydata) {

        initComponents();
        this.mydata = mydata;
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        YtInfoDialog = new javax.swing.JDialog();
        YtInfoTextScrollpane = new javax.swing.JScrollPane();
        YtInfoTextTextArea = new javax.swing.JTextArea();
        YtInfoButtomPanel = new javax.swing.JPanel();
        YtInfoOKButton = new javax.swing.JButton();
        YtMainLabel = new javax.swing.JLabel();
        YtPathTextfield = new javax.swing.JTextField();
        YtChooseButton = new javax.swing.JButton();
        YtButtomPanel = new javax.swing.JPanel();
        YtExportButton = new javax.swing.JButton();
        YtCloseButton = new javax.swing.JButton();
        YtInfoButton = new javax.swing.JButton();

        YtInfoDialog.setMinimumSize(new java.awt.Dimension(461, 251));
        YtInfoDialog.setResizable(false);

        YtInfoTextTextArea.setEditable(false);
        YtInfoTextTextArea.setColumns(20);
        YtInfoTextTextArea.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        YtInfoTextTextArea.setLineWrap(true);
        YtInfoTextTextArea.setRows(5);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("de/ewerkzeug/easytranscript/Core/Bundles/Bundle"); // NOI18N
        YtInfoTextTextArea.setText(bundle.getString("YotubeFrame.YtInfoTextTextArea.text")); // NOI18N
        YtInfoTextTextArea.setWrapStyleWord(true);
        YtInfoTextScrollpane.setViewportView(YtInfoTextTextArea);

        YtInfoOKButton.setText(bundle.getString("YotubeFrame.YtInfoOKButton.text")); // NOI18N
        YtInfoOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YtInfoOKButtonActionPerformed(evt);
            }
        });
        YtInfoButtomPanel.add(YtInfoOKButton);

        javax.swing.GroupLayout YtInfoDialogLayout = new javax.swing.GroupLayout(YtInfoDialog.getContentPane());
        YtInfoDialog.getContentPane().setLayout(YtInfoDialogLayout);
        YtInfoDialogLayout.setHorizontalGroup(
            YtInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(YtInfoButtomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(YtInfoDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(YtInfoTextScrollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addContainerGap())
        );
        YtInfoDialogLayout.setVerticalGroup(
            YtInfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(YtInfoDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(YtInfoTextScrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(YtInfoButtomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        YtInfoDialog.setLocationRelativeTo(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(bundle.getString("YotubeFrame.YtMainLabel.text")); // NOI18N
        setResizable(false);

        YtMainLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        YtMainLabel.setText(bundle.getString("YotubeFrame.YtMainLabel.text")); // NOI18N

        YtPathTextfield.setEditable(false);

        YtChooseButton.setText(bundle.getString("Easytranscript.CPtransReadButton.text")); // NOI18N
        YtChooseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YtChooseButtonActionPerformed(evt);
            }
        });

        YtExportButton.setText(bundle.getString("YotubeFrame.YtExportButton.text")); // NOI18N
        YtExportButton.setEnabled(false);
        YtExportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YtExportButtonActionPerformed(evt);
            }
        });
        YtButtomPanel.add(YtExportButton);

        YtCloseButton.setText(bundle.getString("YotubeFrame.YtCloseButton.text")); // NOI18N
        YtCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YtCloseButtonActionPerformed(evt);
            }
        });
        YtButtomPanel.add(YtCloseButton);

        YtInfoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/ewerkzeug/easytranscript/Core/Images/help-about-3.png"))); // NOI18N
        YtInfoButton.setToolTipText(bundle.getString("YotubeFrame.YtInfoButton.toolTipText")); // NOI18N
        YtInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YtInfoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(YtButtomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(YtMainLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(YtInfoButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(YtPathTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(YtChooseButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(YtMainLabel)
                    .addComponent(YtInfoButton))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YtPathTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YtChooseButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(YtButtomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void YtChooseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YtChooseButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

        fileChooser.setFileFilter(new FileNameExtensionFilter("Youtube Text (.txt)", "txt"));

        fileChooser.setAcceptAllFileFilterUsed(false);
        int ruckgabe = fileChooser.showSaveDialog(null);
        fileChooser.getSelectedFile();
        if (ruckgabe == JFileChooser.CANCEL_OPTION) {

            return;
        }

        String pfad = fileChooser.getSelectedFile().getAbsolutePath();
        if (!pfad.endsWith(".txt")) {
            pfad = pfad + ".txt";
        }

        if (new File(pfad).exists()) {
            int response = JOptionPane.showConfirmDialog(null, messages.getString("WarningOverwrite"), messages.getString("WarningOverwriteTitle"),
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.NO_OPTION) {
                this.YtExportButtonActionPerformed(evt);

            } else if (response == JOptionPane.YES_OPTION) {

            } else if (response == JOptionPane.CLOSED_OPTION) {
                this.YtExportButtonActionPerformed(evt);
            }

        }
        YtPathTextfield.setText(pfad);

        YtExportButton.setEnabled(!pfad.equals(""));

    }//GEN-LAST:event_YtChooseButtonActionPerformed

    private void YtExportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YtExportButtonActionPerformed

        if (!YtPathTextfield.getText().equals("")) {

            try {
                youtube(YtPathTextfield.getText());
            } catch (FileNotFoundException | UnsupportedEncodingException ex) {
                Logger.getLogger(YotubeFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

            dispose();
        }
    }//GEN-LAST:event_YtExportButtonActionPerformed

    private void YtCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YtCloseButtonActionPerformed
        dispose();
    }//GEN-LAST:event_YtCloseButtonActionPerformed

    private void YtInfoOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YtInfoOKButtonActionPerformed
        YtInfoDialog.setVisible(false);
    }//GEN-LAST:event_YtInfoOKButtonActionPerformed

    private void YtInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YtInfoButtonActionPerformed
        YtInfoDialog.setVisible(true);
    }//GEN-LAST:event_YtInfoButtonActionPerformed

    private int youtube(String path) throws FileNotFoundException, UnsupportedEncodingException {
        int count;
        try (PrintWriter writer = new PrintWriter(path, "UTF-8")) {
            Pattern pattern = Pattern.compile("#\\d\\d+:\\d\\d:\\d\\d-\\d#");
            Matcher matcher = pattern.matcher(mydata);
            count = 0;
            int anfang = 0;
            int ende = 0;
            while (matcher.find()) {
                if (anfang == 0 && ende == 0) {
                    writer.print("00:00:00:000,");
                } else {
                    String anfangS = mydata.substring(anfang, ende);
                    anfangS = anfangS.substring(1, anfangS.length() - 1);
                    
                    String milli = anfangS.substring(anfangS.indexOf("-") + 1);
                    
                    anfangS = anfangS.substring(1, anfangS.length() - 2);
                    anfangS = anfangS + "." + milli + "00";
                    writer.print(anfangS + ",");
                }
                anfang = matcher.start();
                
                String text = mydata.substring(ende, anfang);
                text = text.replace("\n", "");
                text = text.replace("\t", "");
                text = text.trim();
                ende = matcher.end();
                String endeS = mydata.substring(anfang, ende);
                endeS = endeS.substring(1, endeS.length() - 1);
                
                String milli = endeS.substring(endeS.indexOf("-") + 1);
                
                endeS = endeS.substring(1, endeS.length() - 2);
                endeS = endeS + "." + milli + "00";
                writer.println(endeS);
                writer.println(text);
                
                count++;
                
                writer.println();
            }
        }

        return count;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel YtButtomPanel;
    private javax.swing.JButton YtChooseButton;
    private javax.swing.JButton YtCloseButton;
    private javax.swing.JButton YtExportButton;
    private javax.swing.JPanel YtInfoButtomPanel;
    private javax.swing.JButton YtInfoButton;
    private javax.swing.JDialog YtInfoDialog;
    private javax.swing.JButton YtInfoOKButton;
    private javax.swing.JScrollPane YtInfoTextScrollpane;
    private javax.swing.JTextArea YtInfoTextTextArea;
    private javax.swing.JLabel YtMainLabel;
    private javax.swing.JTextField YtPathTextfield;
    // End of variables declaration//GEN-END:variables
}
